
services:
  db:
    image: postgres:15-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword   # << แก้ให้ตรงกับที่อยากใช้
      POSTGRES_DB: dorm_booking         # << ชื่อ DB ที่ backend ใช้
    ports:
      - "5432:5432"
    volumes:
      # เก็บ data ถาวร
      - postgres_data:/var/lib/postgresql/data
      # ให้ init.sql รันตอนสร้าง DB ครั้งแรก
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
